apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  type: oci  # Specify the repository type as OCI
  interval: 5m
  url: oci://ghcr.io/kyverno/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  interval: 5m
  chart:
    spec:
      chart: kyverno  # Chart name inside the OCI registry
      version: "3.3.7" 
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment