apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  interval: 5m
  chart:
    spec:
      chart: oci://ghcr.io/kyverno/charts/kyverno
      version: "sha256-5ad23b9f0540fdecbeb37e006f2b8baf524fd7b8ff30d65f88654b0faf57365f"  # Replace with the actual digest
  install:
    createNamespace: true