apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  type: oci  # Specify the repository type as OCI
  interval: 5m
  url: oci://ghcr.io/kyverno/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  releaseName: kyverno
  targetNamespace: kyverno
  interval: 5m
  chart:
    spec:
      chart: kyverno  # Chart name inside the OCI registry
      version: "sha256:5ad23b9f0540fdecbeb37e006f2b8baf524fd7b8ff30d65f88654b0faf57365f"  # Replace with actual SHA
      sourceRef:
        kind: HelmRepository
        name: kyverno
  install:
    createNamespace: true