apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: check-image-notary
spec:
  webhookConfiguration:
    failurePolicy: Fail
    timeoutSeconds: 30
  rules:
    - name: verify-signature-notary
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - type: Notary
        imageReferences:
        //- "ghcr.io/iheartnathan/net-monitor*"
        - "*"
        failureAction: Enforce
        attestors:
        - count: 1
          entries:
          - certificates:
              cert: |-
                    -----BEGIN CERTIFICATE-----
                    MIIDSDCCAjCgAwIBAgIBTTANBgkqhkiG9w0BAQsFADBTMQswCQYDVQQGEwJVUzEL
                    MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEU
                    MBIGA1UEAxMLdGVzdC1lbnYuaW8wHhcNMjUwMzE2MjMyOTQ4WhcNMjUwMzE3MjMy
                    OTQ4WjBTMQswCQYDVQQGEwJVUzELMAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0
                    bGUxDzANBgNVBAoTBk5vdGFyeTEUMBIGA1UEAxMLdGVzdC1lbnYuaW8wggEiMA0G
                    CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZvsEkmPsy4ZwvXO/RpMfQjZDWSTy0
                    JHbWjs9jW2/KXnrORBjAslIOEoJetGCTCmC+39B69mpo5VEk75uy0Rgqpx1tbbJP
                    ycUg8MskZwCyrHynTrPu6yhzXvPrFZtYNTp2FmgA2z3Vr39dzWa9MwWPuttak+gT
                    IKKVRH5g1j/wmljkiBjRVzH6JsUkGP5/uvRM2SZQihVIuBjorcGBe787PUnQ2+0K
                    A9zUrvzp0UDUz3mDXoQmr/sFg5dZZ2Zq5/YvIPbYfcaC67zTVGcB5US7Jh9szeiH
                    ksbYYfEcAZgNZ82Un0/aMj/K0YiF2MIsBrt+u1CQf6lQSwoPBx2UiyEZAgMBAAGj
                    JzAlMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzANBgkqhkiG
                    9w0BAQsFAAOCAQEAGmXVHsIMr6GE7pFlTkPxVQDnLA4wHep92/FUJyqlx8QvDK73
                    BtIVMCwoj4kcCGvRrL1fx3F3OTZxv/vY2SQsLjcfzDjenWbF3uJ9htCW1KGV+asB
                    6moj/LZZZR/rrzLbfMlnGpKAMAlbzqHiprBSNUEC9m/7J1FZ5NiWfAsMfb67EW8x
                    2cIxxAdCNph2fBPkIKh+R29DjNSFJhDDdM4Pr4jH+uApuzGdlGYc28QtLJa7+oah
                    JygacuMT+CTbd2IVSboZ9ZM/CB/xGGfrjnIqFQqBhleMECMZCOewC/CwtG9gIYLV
                    Wzbk3aT+jzbpisNGiVPaNA52kc0VZiMj760CTg==
                    -----END CERTIFICATE-----

    