name: OCI Image Layout / Supply Chain Artifacts Workflow

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    outputs:
      image_tag: echo "edinburgh:v1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Build Docker Image as OCI Layout
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: Dockerfile
          outputs: type=oci,dest=output.tar
          tags: edinburgh:v1
          platforms: linux/amd64,linux/arm64
          provenance: false

      - name: Extract OCI image layout
        run: |
          mkdir edinburgh
          tar -xf output.tar -C edinburgh
          ls -lha edinburgh/blobs/sha256 || true
          cat edinburgh/index.json | jq

      - name: Run Trivy vulnerability scan (JSON)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          input: edinburgh:v1
          format: json
          output: trivy-vulnerability-scan.json

      - name: Upload vulnerability scan
        uses: actions/upload-artifact@v4
        with:
          name: trivy-vulnerability-scan-json
          path: trivy-vulnerability-scan.json


  sbom:
    needs: build-and-scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: [spdx-json, cyclonedx]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Generate SBOM using Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          input: edinburgh:v1
          format: ${{ matrix.format }}
          output: image-sbom-${{ matrix.format }}.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.format }}-sbom
          path: image-sbom-${{ matrix.format }}.json
